[package]
name = "db_work"
version = "0.1.0"
authors = ["Locke <moyerock@gmail.com>"]

[dependencies]
diesel = { version = "1.2.2", features = ["postgres"] }
dotenv = "0.12.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
