[package]
name = "wasm_demo"
version = "0.1.0"
authors = ["Locke <moyerock@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.8"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
